### ISSUE TITLE
Where are user accounts stored?

### ISSUE THREAD

**Issue by davidnewhall** [mtlynch/mediagoblin-docker#48]
Hello,

I'm new to media goblin, and this is probably a total noob question. I'm running media goblin in unRAID (with this Docker container). I've mapped the media path, but I'm wondering where the user accounts are stored, and how I can make sure they are persisted through container upgrades. Maybe I need more documentation on "how to maintain this Docker image," and I'm just not able to find it. Any help or pointers are appreciated!

EDIT: Twice now I've changed mounted paths on my container and it's blown away my user account and admin password. How do I avoid that?

I also left a comment on _this_ pull request. I think I'm running into a bug.. https://github.com/mtlynch/mediagoblin-docker/pull/46/files#diff-8742b88fc99029dc5d3859a7242c5208R20

Thank you!

**Comment by mtlynch** [comment]
They're stored in `mediagoblin.db`. By default, that file is in `/srv/mediagoblin.example.org/mediagoblin/mediagoblin.db`, but in my workflows, I modify `mediagoblin.ini` so that `sql_engine` points to a different location. See my example here:

https://mtlynch.io/digitizing-home-videos-walkthrough/#create-mediagoblin-files

I apologize, as it's not very clear or intuitive. I tried to do as little as possible in the Docker image to poke around at MediaGoblin's internals, but that results in challenging workflows because MediaGoblin core is not very flexible.

This docker image isn't actively maintained, as I've been trying for literally years to get these changes merged into MediaGoblin upstream, but nobody is maintaining that project anymore. There are little bursts of work every 6-12 months, but they're just too limited in bandwidth to accept external contributions, in my experience.

**Comment by davidnewhall** [comment]
Thank you for the info! <3
