### ISSUE TITLE
Persistent install?

### ISSUE THREAD

**Issue by PiDockMedia** [mtlynch/mediagoblin-docker#49]
I am trying to figure out how to install this with a persistent copy of all the important files outside of the container. I tried simply mapping /srv/mediagoblin.example.org/mediagoblin to an external directory but that caused the install to fail. As /srv/mediagoblin.example.org/mediagoblin only exists in  the container, if I try and update the container will that not get destroyed? Even though my content will be safe I believe the database of what is actually in Mediagoblin along with users etc will be destroyed. Am I missing something?

**Comment by mtlynch** [comment]
In my workflows, I modify `mediagoblin.ini` so that `sql_engine` points to a different location. See my example here:

https://mtlynch.io/digitizing-home-videos-walkthrough/#create-mediagoblin-files

I apologize, as it's not very clear or intuitive. I tried to do as little as possible in the Docker image to poke around at MediaGoblin's internals, but that results in challenging workflows because MediaGoblin core is not very flexible.

This docker image isn't actively maintained, as I've been trying for literally years to get these changes merged into MediaGoblin upstream, but nobody is maintaining that project anymore. There are little bursts of work every 6-12 months, but they're just too limited in bandwidth to accept external contributions, in my experience.

**Comment by mtlynch** [comment]
Out of curiosity, what prompted this sudden flurry of interest? This repo's been up for ~2 years, and nobody has engaged with it at all, then suddenly there have been two issues in a couple days.

**Comment by PiDockMedia** [comment]
For me flickr and smugmug have not been really updated in many years and so I am testing options for hosting my pictures myself. Being a big fan of docker I went looking for a container and here I am. :-)
